### ISSUE TITLE
Reinvent 3.0: bucket_size missing from diversityfilter

### ISSUE THREAD

**Issue by j3mdamas** [MolecularAI/ReinventCommunity#11]
Hi,

It seems that the new Reinvent requires a parameter for the diversity filter called `bucket_size`, and it fails if it doesn't have it.

Adding it to the input.json fixes the issue.

**Comment by j3mdamas** [comment]
Related with this, I think, is that the version parameter of the JSON passed to the input.py is still 2 on all the examples. This parameter could help with distinguishing the input needs of each version of reinvent associated with it.

**Comment by patronov** [comment]
Hi, 

Yes, that was the original purpose of versioning but we decided to drop the backward compatibility. Good point though as we can use it (and should) for versioning the configs to prevent confusion. In the future releases the missing keyword for bucket size wont be an issue since we will assign a default value. We havent rolled out the latest versions to the public git though. There will be a few breaking changes as it turns and we will aim to time it all at once.

**Comment by j3mdamas** [comment]
@patronov Thanks. We'll wait for the public release then, meanwhile we're able to work-around it.

**Comment by patronov** [comment]
> Related with this, I think, is that the version parameter of the JSON passed to the input.py is still 2 on all the examples. This parameter could help with distinguishing the input needs of each version of reinvent associated with it.

@GuoJeff could you please help with incrementing the versions in the example inputs. I think they mostly state v 2.0
