### ISSUE TITLE
How long does it take to train a new prior network?

### ISSUE THREAD

**Issue by JinChengneng** [MolecularAI/ReinventCommunity#2]
Hi there! I am really interested in your repository and thanks a lot for your sharing.

I am trying to train a new prior network such as ``` `augmented.prior` ``` by running ```Transfer_Learning_Demo_Teachers_forcing.ipynb```. However, I find it's extremely time consuming. It takes almost 7 hours for me to run a single epoch. I wonder whether these codes could run in GPU. Moreover, I would appreciate it if you could provide some information about the configuration of your machine for training and the time it takes to run an epoch. Thanks again.

**Comment by patronov** [comment]
Hi, and thanks for the interest!
Regarding the training of a generative model from scratch it is advisable to do it on GPU. I believe this particular model was trained on Nvidia Geforce RTX 2080 and one epoch took ~ 10 mins. The model we have released is trained for about ~250 epochs. Which is quite the overkill since with large dataset you could settle for something thats simply maxes out the validity to ~98% and that should be enough for practical purposes. I believe the model we release gives validity of >99%.
Anyway, I hope this information helps. Please, let us know if you have any other questions.

**Comment by JinChengneng** [comment]
Thanks a lot for your response!  
I've done the training process on GPU and it runs much faster. I also have implemented an early stop policy according to a target validity ratio, which is really useful. Thanks again for your help.
